version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass supersecurepassword
  web:
    build: .
    environment:
      PORT: "5000"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "supersecurepassword"
    ports:
      - "5000:5000"
