version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass supersecurepassword
  web:
    build: .
    environment:
      PORT: "5000"
      REDIS_URL: 'redis://:supersecurepassword@redis:6379'
    ports:
      - "5000:5000"
